name: CI
on:
  push:
    branches: 
      - master
  pull_request_target:
    types:
      - closed
    branches:
      - master
jobs:
  myjob:
    name: Build and Deploy
    if: |
      github.event.pull_request_target.merged == true || 
      github.event_name == 'push'
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - uses: webfactory/ssh-agent@v0.5.4
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Install Publish
      run: |
        git clone git@github.com:hung-m-dao/my-publish.git
        cd my-publish
        make
    - name: Generate HTML
      run: publish generate
    - name: Deploy
      run: publish deploy