name: CI
on:
  push:
  pull_request_target:
    types:
      - closed
jobs:
  myjob:
    name: Build and Deploy
    if: |
      github.event.pull_request_target.merged == true || 
      github.event_name == 'push'
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Publish
      run: brew install publish
    - uses: webfactory/ssh-agent@v0.5.4
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Generate HTML
      run: publish generate
    - name: Deploy
      run: publish deploy